name: Create and Push Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Geode CLI
      run: |
        wget https://github.com/geode-sdk/cli/releases/download/v2.6.1/geode-cli-v2.6.1-linux.zip
        unzip geode-cli-v2.6.1-linux.zip
        sudo mv geode-cli /usr/local/bin/geode

    - name: Create Geode Mod
      run: geode new MyAwesomeMod

    - name: Commit and Push
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Create new Geode mod"
        git push
